Set contribution invoice ID after Contribution.completetransaction
agileware/au.com.agileware.ewayrecurring pull request #18
Opened 2021-06-22 00:50 UTC by AsylumSeekersCentre

This corrects the error in my previous pull request. It has not yet been tested, the first test of this code pathway should occur tonight on our test server.

The purpose of this change is to set the invoice_id for transactions which are completed by Contribution.completetransaction.

2021-06-24 02:38 UTC, AsylumSeekersCentre commented
I can now confirm that this code has set the invoice ID correctly for the last two nights (running in Test mode).

2021-08-05 03:47 UTC, agileware-fj requested changes

2021-08-05 03:47 UTC, agileware-fj commented on eWAYRecurring.process.inc
> +      watchdog('updated', json_encode($updated));
Please remove debugging statements

2021-08-05 04:36 UTC, AsylumSeekersCentre commented
I've just removed those lines. Would you like me to apply all of the changes to a new branch, and open a new pull request with a single commit?

2021-08-05 05:03 UTC, agileware-fj commented
Single commit would be better - you should be able to do this by squashing the commits together, then `git push --force-with-lease` to the same branch on github.

2021-08-05 05:14 UTC, AsylumSeekersCentre commented
Great, thank you for explaining how to do that. I've squashed the commits and it now looks correct to me.

2021-09-14 23:16 UTC, merged